#!/usr/bin/env bash

shopt -s nullglob

# Utility functions {{{
  # Logging {{{
    ansi_reset="$(tput sgr0 || true)"
    ansi_red="$(tput setaf 1 || true)"
    ansi_yellow="$(tput setaf 3 || true)"
    ansi_blue="$(tput setaf 4 || true)"
    ansi_green="$(tput setaf 2 || true)"
    log_info()    { echo >&2 "${ansi_blue}[info]${ansi_reset}" "$@"; }
    log_warn()    { echo >&2 "${ansi_yellow}[warn]${ansi_reset}" "$@"; }
    log_error()   { echo >&2 "${ansi_red}[ERROR]${ansi_reset}" "$@"; }
    log_success() { echo >&2 "${ansi_green}[success]${ansi_reset}" "$@"; }

    # Use the log_error function to indicate where an error occurs
    trap 'log_error line $LINENO' ERR
  # }}}

    # Checks for command on path
    command_exists() { whence -- "$@" &> /dev/null; }
# }}}

# Preliminary checks {{{
    if command_exists repo-add; then
        log_error "Package 'aurutils' is not installed!"
        exit 1
    fi
# }}}

if [ -f ~/.aurbuild ]; then
    source ~/.aurbuild
else
    echo "configuration file not found:"
    echo "$ cat ~/.aurbuild
repository_name=repo_name_here
repository_location=/foo/\$repository_name/\$(uname -m)/
"
    exit 1
fi

location="$(pwd)"
repository_location="${repository_location%?}"

function released_version {
    name=$1

    pacman -Ss $name | grep -e "^$repository_name/$name " | cut -d" " -f2
}

if ! [ -f "$repository_location/$repository_name.db.tar.gz" ]; then
    echo "repo db not found, creating..."
    cd "$repository_location"
    repo-add "$repository_name.db.tar.gz"
fi


packages=()
echo "initializing build queue"
for name in $(find . -mindepth 1 -maxdepth 1 -type d -not -name "\.*"); do
    source $(basename $name)/PKGBUILD

    package=$pkgname
    local_version="${pkgver}-${pkgrel}"
    remote_version="$(released_version $package)"

    if [ -f $package/.norelease ]; then
        echo "  disabled: $package (explicit)"
    elif [ "$local_version" == "$(echo -e "$local_version\n$remote_version" | sort -V | head -n1)" ]; then
        echo "  disabled: $package (local version $local_version <= remote version $remote_version)"
    elif [[ ! " ${arch[*]} " =~ " any " ]] && [[ ! " ${arch[*]} " =~ " $(uname -m) " ]]; then
        echo "  disabled: $package (arch not targeted in PKGBUILD: $(uname -m))"
    else
        echo "  enabled: $package ($local_version)"
        packages+=($package)
    fi
done

failures=()
for package in ${packages[@]}; do
    cd "$location/$package"

    makepkg $*

    if [ $? -eq 0 ]; then
        rsync -avhP *.tar.zst $repository_location
        rsync -avhP *.tar.zst.sig $repository_location
    else
        failures+=($package)
    fi
done

if [ -n "$auto_update" ]; then
    cd "$repository_location"
    for pkg in "$repository_location"/*.pkg.tar.zst; do
        repo-add -n "$repository_name.db.tar.gz" "$pkg"
    done
fi

cd "$location"

if [ ${#failures[@]} -gt 0 ]; then
    echo "failed to build ${#failures[@]} package(s):"
    for package in ${failures[@]}; do
        echo "  $package"
    done
    exit 1
fi
